name: "ci"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-editorconfig-checker:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.2.1"
      - uses: "editorconfig-checker/action-editorconfig-checker@main"
      - run: "editorconfig-checker"

  ci:
    runs-on: "ubuntu-latest"
    container: "theoludwig/gcc-make-doxygen-ubuntu:latest"

    strategy:
      matrix:
        task: [TP1, TP2]

    steps:
      - uses: "actions/checkout@v4.2.1"

      - run: "make"
        working-directory: ${{ matrix.task }}

      - run: "make lint"
        working-directory: ${{ matrix.task }}

      - run: "make clean"
        working-directory: ${{ matrix.task }}
